name: Docker Image

on:
  push:
    branches:
      - master
  schedule:
    - cron: '20 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout upstream repo
        uses: actions/checkout@v2
        with:
          repository: tdlib/telegram-bot-api
          path: telegram-bot-api
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Get current time
      #   uses: 1466587594/get-current-time@v2
      #   id: current-time
      #   with:
      #     format: YYYYMMDD
      - name: Set version
        id: current-version
        run: |
          TG_SERVER_VERSION=$(cat telegram-bot-api/CMakeLists.txt | grep TelegramBotApi | cut -d " " -f3)
          echo "TG_SERVER_VERSION=${TG_SERVER_VERSION}" >> $GITHUB_ENV
          echo "Parsed version: ${TG_SERVER_VERSION}"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/amd64,linux/arm
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_LOGIN }}/telegram-bot-api:latest
            ${{ secrets.DOCKERHUB_LOGIN }}/telegram-bot-api:${{ env.TG_SERVER_VERSION }}
          #  ${{ secrets.DOCKERHUB_LOGIN }}/telegram-bot-api:${{ steps.current-time.outputs.formattedTime }}
